title: O'Shae Felix
logo: /Assets/headshot.jpeg.png
description: I am a graduate from Tarleton State University in Indistrial Technology with a background in Power currently a Real Time Trader at bp passionate about energy and coding. In the past I have worked roled in power generation facilaties mainly cobined cycle and nuclear.
#show_downloads: true

theme: jekyll-theme-minimal
